USE app;

CREATE DATABASE IF NOT EXISTS app;
CREATE USER IF NOT EXISTS app;
GRANT ALL ON DATABASE app TO app;

CREATE TABLE IF NOT EXISTS test (
    id SERIAL PRIMARY KEY,
    value VARCHAR NOT NULL
);
